name: Publish Docker image

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

    - name: Build and push Docker image
      run: |
        docker -v
        docker build -t my-image .
        docker tag my-image $DOCKER_USERNAME/my-image:latest
        docker push $DOCKER_USERNAME/my-image:latest
